# VIRULE Client build stages. THIS SCRIPT NEVER SIGNS - signing is
# centralized in D:\Dropbox\Dropbox\development\VIRULE_SECURITY\artifact-signing
# (sign_client.bat / sign_client_setup.bat).
#
# RELEASE ORDER (a hard rule, because Setup EMBEDS the SIGNED client):
#   1. helpers\build.ps1 -Stage client          build virule-client.exe
#   2. VIRULE_SECURITY\artifact-signing\sign_client.bat          sign it
#   3. helpers\build.ps1 -Stage setup           stage the SIGNED client into
#                                               src\setup\payload + bake its
#                                               SHA-256, build Virule-Setup.exe
#   4. VIRULE_SECURITY\artifact-signing\sign_client_setup.bat    sign Setup
#      (its gate verifies the client embedded in Setup IS the signed client)
#
# -Stage all (the default) is the UNSIGNED development flow: the same order
# in one pass with no signing in between. Such a Setup installs only with
# --dev-unsigned (the payload hash gate always holds; only the Authenticode
# gate is waived).
#
# Usage:  powershell -ExecutionPolicy Bypass -File helpers\build.ps1 [-Stage all|client|setup]

param(
    [ValidateSet('all', 'client', 'setup')]
    [string]$Stage = 'all'
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

function Find-MSBuild {
    $candidates = @(
        'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe',
        'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe',
        'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe'
    )
    foreach ($c in $candidates) { if (Test-Path $c) { return $c } }
    throw 'MSBuild.exe not found'
}

$msbuild = Find-MSBuild
$clientExe = Join-Path $repo 'build\Release\x64\virule-client.exe'
$setupExe  = Join-Path $repo 'build\Release\x64\Virule-Setup.exe'
$payloadDir = Join-Path $repo 'src\setup\payload'
$payloadExe = Join-Path $payloadDir 'virule-client.exe'
$hashHeader = Join-Path $payloadDir 'payload_hash.h'

function Build-Client {
    Write-Host '=== build virule-client.exe ==='
    & $msbuild (Join-Path $repo 'client\virule_client.vcxproj') /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="$repo\" /nologo /v:minimal
    if ($LASTEXITCODE -ne 0) { throw 'client build failed' }
    if (-not (Test-Path $clientExe)) { throw "client build produced no exe: $clientExe" }
}

function Build-Setup {
    if (-not (Test-Path $clientExe)) { throw "client exe not found (run -Stage client first): $clientExe" }

    $sig = Get-AuthenticodeSignature $clientExe
    if ($sig.Status -eq 'Valid') {
        Write-Host "staging SIGNED client (signer: $($sig.SignerCertificate.Subject))"
    } else {
        Write-Host "WARNING: staging UNSIGNED client (Authenticode: $($sig.Status))." -ForegroundColor Yellow
        Write-Host '         Development only - this Setup installs solely with --dev-unsigned.' -ForegroundColor Yellow
        Write-Host '         For release, sign the client FIRST (sign_client.bat), then re-run -Stage setup.' -ForegroundColor Yellow
    }

    Write-Host '=== stage payload + bake hash ==='
    New-Item -ItemType Directory -Force $payloadDir | Out-Null
    Copy-Item $clientExe $payloadExe -Force
    $hash = (Get-FileHash -Algorithm SHA256 $payloadExe).Hash.ToLowerInvariant()
    @"
#pragma once
// GENERATED by helpers/build.ps1. SHA-256 of the exact client payload
// embedded in Virule-Setup.exe; Setup refuses any payload that does not
// match. Do not edit by hand.
inline constexpr const char* kClientPayloadSha256Hex =
    "$hash";
"@ | Out-File -Encoding ascii $hashHeader
    Write-Host "payload sha256: $hash"

    Write-Host '=== build Virule-Setup.exe ==='
    & $msbuild (Join-Path $repo 'setup\virule_setup.vcxproj') /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="$repo\" /nologo /v:minimal
    if ($LASTEXITCODE -ne 0) { throw 'setup build failed' }
    if (-not (Test-Path $setupExe)) { throw "setup build produced no exe: $setupExe" }
}

switch ($Stage) {
    'client' {
        Build-Client
        Write-Host ''
        Write-Host 'DONE (stage: client)'
        Write-Host "  client: $clientExe"
        Write-Host 'Next: sign it via VIRULE_SECURITY\artifact-signing\sign_client.bat,'
        Write-Host 'then run helpers\build.ps1 -Stage setup.'
    }
    'setup' {
        Build-Setup
        Write-Host ''
        Write-Host 'DONE (stage: setup)'
        Write-Host "  setup : $setupExe"
        Write-Host 'Next: sign it via VIRULE_SECURITY\artifact-signing\sign_client_setup.bat.'
    }
    'all' {
        Build-Client
        Build-Setup
        Write-Host ''
        Write-Host 'DONE (unsigned development build)'
        Write-Host "  client: $clientExe"
        Write-Host "  setup : $setupExe"
    }
}
