# VIRULE Client build orchestration.
#
# Order (a hard rule, because Setup embeds the SIGNED client):
#   1. build virule-client.exe
#   2. sign virule-client.exe                (-Sign; helpers\sign.ps1)
#   3. stage the signed client into src\setup\payload\ + bake its SHA-256
#   4. build Virule-Setup.exe
#   5. sign Virule-Setup.exe                 (-Sign)
#
# Without -Sign the same order runs unsigned (development builds; Setup
# then only installs with --dev-unsigned).
#
# Usage:  powershell -ExecutionPolicy Bypass -File helpers\build.ps1 [-Sign]

param(
    [switch]$Sign
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot

function Find-MSBuild {
    $candidates = @(
        'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe',
        'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe',
        'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe'
    )
    foreach ($c in $candidates) { if (Test-Path $c) { return $c } }
    throw 'MSBuild.exe not found'
}

$msbuild = Find-MSBuild
$clientExe = Join-Path $repo 'build\Release\x64\virule-client.exe'
$setupExe  = Join-Path $repo 'build\Release\x64\Virule-Setup.exe'
$payloadDir = Join-Path $repo 'src\setup\payload'
$payloadExe = Join-Path $payloadDir 'virule-client.exe'
$hashHeader = Join-Path $payloadDir 'payload_hash.h'

Write-Host '=== 1. build virule-client.exe ==='
& $msbuild (Join-Path $repo 'client\virule_client.vcxproj') /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="$repo\" /nologo /v:minimal
if ($LASTEXITCODE -ne 0) { throw 'client build failed' }
if (-not (Test-Path $clientExe)) { throw "client build produced no exe: $clientExe" }

if ($Sign) {
    Write-Host '=== 2. sign virule-client.exe ==='
    & powershell -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'sign.ps1') -File $clientExe
    if ($LASTEXITCODE -ne 0) { throw 'client signing failed' }
} else {
    Write-Host '=== 2. (unsigned development build; -Sign skipped) ==='
}

Write-Host '=== 3. stage payload + bake hash ==='
New-Item -ItemType Directory -Force $payloadDir | Out-Null
Copy-Item $clientExe $payloadExe -Force
$hash = (Get-FileHash -Algorithm SHA256 $payloadExe).Hash.ToLowerInvariant()
@"
#pragma once
// GENERATED by helpers/build.ps1. SHA-256 of the exact client payload
// embedded in Virule-Setup.exe; Setup refuses any payload that does not
// match. Do not edit by hand.
inline constexpr const char* kClientPayloadSha256Hex =
    "$hash";
"@ | Out-File -Encoding ascii $hashHeader
Write-Host "payload sha256: $hash"

Write-Host '=== 4. build Virule-Setup.exe ==='
& $msbuild (Join-Path $repo 'setup\virule_setup.vcxproj') /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="$repo\" /nologo /v:minimal
if ($LASTEXITCODE -ne 0) { throw 'setup build failed' }
if (-not (Test-Path $setupExe)) { throw "setup build produced no exe: $setupExe" }

if ($Sign) {
    Write-Host '=== 5. sign Virule-Setup.exe ==='
    & powershell -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'sign.ps1') -File $setupExe
    if ($LASTEXITCODE -ne 0) { throw 'setup signing failed' }
} else {
    Write-Host '=== 5. (unsigned development build; -Sign skipped) ==='
}

Write-Host ''
Write-Host "DONE"
Write-Host "  client: $clientExe"
Write-Host "  setup : $setupExe"
